public class Dynamicsql {
    
    Public void dhoom()
    {   //String dynQuery accountClass ='Class1';
       // String dynQuery = 'SELECT Id, Name From Account';
        //if(accountType == 'Red'){
          //  dynQuery +='where Rating =\'Hot'\ and Amoutn>100000;
       String accountClass ='Class1';
        String queryString = 'SELECT ID, Name, Phone, Rating FROM Account';
        
            
        }
        
        
    }