public class Settest {
    public void dup()
        
    {
        //use for shorting and alphbatically shortin and integer shorting 
        set <string> ss1 = new set <string>{'rahul','nigam','jaiswal','asd'};
            system.debug(ss1);
        set <string> ss2 = new set <string>{'rahul','nigam','jaiswal','asd','54ram','Rahul'};
            system.debug(ss2);
        set <string> ss3 = new set <string>{'rahul548','nigam','jaiswal','001asd','54ram','Rahul'};
            system.debug(ss3);
        set <string> ss4 = new set <string>{'rahul548','nigam','jaiswal','001asd','54ram','Rahul'};
integer s3=ss1.size();
system.debug(s3);        






            
    }

}