public class WWE {
    
    Public Void miss()
    {
        
        Account few = New account();
        few.Name = 'rathore';
        //Account tns = New account();
       // tns.Name ='ramayan1';
                insert few;
                   // insert tns;
           
 //List<Account> Fetch = New List<Account>();
      //  Fetch = [Select ID, Name from Account limit 1];
       // system.debug(Fetch);
    }

}